services:
  - type: web
    name: movie-recommendation-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run startCommand --server.port $PORT --server.enableCORS false
    plan: free
